### ISSUE TITLE
hello,yfgeek

### ISSUE THREAD

**Issue by Biggg888** [yfgeek/NUC5i5RYH-DSDT-Patch#4]
我的nuc5i5ryb的蓝牙驱动不成功，WiFi有时候也很难脸上，可以请教一下是什么问题吗？

**Comment by yfgeek** [comment]
不是一个型号的，需自行寻找对应的蓝牙驱动

**Comment by Biggg888** [comment]
> 不是一个型号的，需自行寻找对应的蓝牙驱动

Thank you
